### ISSUE TITLE
Access to globalToLocal and localToGlobal  methods

### ISSUE THREAD

**Issue by Yoann53** [dankuck/vue-easeljs#5]
Hi danckuk, thank you very much for your library. It's ideal for my project.

I need to access to globalToLocal and localToGlobal method from a container.
For the moment, I need to go through MouseEvent to access to them :
evt.currentTarget.parent.localToGlobal
I cannot do this via this.$refs.container.localToGlobal.

Any idea ? Thanks

**Comment by dankuck** [comment]
Hi Yoann, thanks for the kind words.

I'm glad you found one way to get at what you need.

I think using $refs could still get you to a solution. Can you post an example of what you tried?

**Comment by Yoann53** [comment]
Yes, I have this code in my template :
<easel-container
          :x="containerMap.x"
          :y="containerMap.y"
          :scale="containerMap.scale"
          :rotation="containerMap.rotation"
          ref="container"
        >
I tried that to access to container methods (documented in esaeljs doc):
this.$refs.container.localToGlobal(...)
and
this.$refs.container.$el.localToGlobal(...)

Same error : TypeError: this.$refs.container.$el.localToGlobal is not a function

Could you help me ?

Thanks

**Comment by Yoann53** [comment]
Sorry for my previous question.
I find attribute 'component' !

So the solution is in $refs like you said. 
this.$refs.container.component.localToGlobal(x, y) works fine !

**Comment by dankuck** [comment]
Great! I'm glad you found the solution. Keep in touch. :)
